package com.example.urlshortener.orchestrator;
import org.springframework.stereotype.Service; import java.util.*; import java.util.concurrent.*;
@Service public class WorkflowEngine {
 private final ApprovalGate approvals; private final PolicyGuard policies; private final AuditTrail audit; private final WorkflowMetrics metrics; private final ConcurrentMap<String,WorkflowInstance> store=new ConcurrentHashMap<>();
 public WorkflowEngine(ApprovalGate a,PolicyGuard p,AuditTrail t,WorkflowMetrics m){approvals=a;policies=p;audit=t;metrics=m;}
 public String create(WorkflowScenario scenario,String requirement,List<WorkflowTask> tasks){validateGraph(tasks);String id=UUID.randomUUID().toString();store.put(id,new WorkflowInstance(id,scenario,new ExecutionContext(id,requirement),tasks));audit.record(id,"WORKFLOW","CREATED",scenario+": "+requirement);return id;}
 public WorkflowStatus execute(String id){WorkflowInstance w=get(id); synchronized(w){if(!w.metricsStarted){metrics.started();w.metricsStarted=true;}w.status=WorkflowStatus.RUNNING;
   while(true){List<WorkflowTask> ready=w.tasks().values().stream().filter(t->t.status()==TaskStatus.PENDING&&dependenciesComplete(t,w)).toList();
     if(ready.isEmpty())break; boolean approvalBlock=false;
     for(WorkflowTask t:ready){if(t.requiresApproval()&&!approvals.approved(id,t.id())){t.status(TaskStatus.WAITING_FOR_APPROVAL);approvals.request(id,t.id());audit.record(id,t.id(),"APPROVAL_REQUIRED",t.name());approvalBlock=true;}}
     List<WorkflowTask> executable=ready.stream().filter(t->t.status()==TaskStatus.PENDING).toList();
     if(!executable.isEmpty() && !runParallelBatch(w,executable)){w.status=WorkflowStatus.FAILED;rollbackCompleted(w);metrics.failed();return w.status;}
     if(approvalBlock){w.status=WorkflowStatus.WAITING_FOR_APPROVAL;return w.status;}
   }
   if(w.tasks().values().stream().allMatch(t->t.status()==TaskStatus.COMPLETED)){w.status=WorkflowStatus.COMPLETED;metrics.completed(System.nanoTime()-w.createdNanos);audit.record(id,"WORKFLOW","COMPLETED","All exit gates satisfied");}
   else if(w.tasks().values().stream().anyMatch(t->t.status()==TaskStatus.WAITING_FOR_APPROVAL))w.status=WorkflowStatus.WAITING_FOR_APPROVAL;
   else {w.status=WorkflowStatus.SAFE_STOPPED;audit.record(id,"WORKFLOW","SAFE_STOPPED","No eligible tasks remain");}
   return w.status; }}
 private boolean runParallelBatch(WorkflowInstance w,List<WorkflowTask> tasks){
   if(tasks.size()==1)return runTask(w,tasks.get(0)); audit.record(w.id(),"WORKFLOW","PARALLEL_BATCH","Executing ready nodes in parallel: "+tasks.stream().map(WorkflowTask::id).toList());
   try(ExecutorService executor=Executors.newVirtualThreadPerTaskExecutor()){List<Future<Boolean>> futures=tasks.stream().map(t->executor.submit(()->runTask(w,t))).toList();boolean ok=true;for(Future<Boolean> f:futures){try{ok &= f.get();}catch(InterruptedException e){Thread.currentThread().interrupt();return false;}catch(ExecutionException e){ok=false;}}return ok;}
 }
 private boolean runTask(WorkflowInstance w,WorkflowTask t){policies.validate(t);t.status(TaskStatus.RUNNING);for(int i=t.attempts();i<t.maxAttempts();i++){int attempt=t.incrementAttempts();audit.record(w.id(),t.id(),"STARTED",t.agent().name()+" attempt="+attempt);try{AgentResult r=t.agent().execute(w.context());if(!r.success())throw new IllegalStateException(r.summary());r.artifacts().forEach(w.context()::putArtifact);t.status(TaskStatus.COMPLETED);audit.record(w.id(),t.id(),"COMPLETED",r.summary());return true;}catch(Exception e){t.lastError(e.getMessage());audit.record(w.id(),t.id(),"ATTEMPT_FAILED",e.getMessage());if(attempt<t.maxAttempts()){metrics.retry();audit.record(w.id(),t.id(),"RETRY","bounded retry with exponential backoff");try{Thread.sleep(Math.min(500L,50L*(1L<<(attempt-1))));}catch(InterruptedException x){Thread.currentThread().interrupt();break;}}}}t.status(TaskStatus.FAILED);audit.record(w.id(),t.id(),"FAILED","retry budget exhausted; no safe fallback was applicable");return false;}
 private void rollbackCompleted(WorkflowInstance w){List<WorkflowTask> list=new ArrayList<>(w.tasks().values());Collections.reverse(list);for(WorkflowTask t:list){if(t.status()==TaskStatus.COMPLETED&&(t.id().equals("IMPL")||t.id().equals("RELEASE"))){try{t.rollback().run();t.status(TaskStatus.ROLLED_BACK);metrics.rollback();audit.record(w.id(),t.id(),"ROLLED_BACK","Compensating action executed");}catch(Exception e){audit.record(w.id(),t.id(),"ROLLBACK_FAILED",e.getMessage());}}}}
 public void approve(String workflowId,String taskId){WorkflowInstance x=get(workflowId);WorkflowTask task=Optional.ofNullable(x.tasks().get(taskId)).orElseThrow(()->new IllegalArgumentException("Unknown task: "+taskId));approvals.approve(workflowId,taskId);if(task.status()==TaskStatus.WAITING_FOR_APPROVAL)task.status(TaskStatus.PENDING);audit.record(workflowId,taskId,"APPROVED","Human approval received");}
 public void replan(String id,String newRequirement,String fromTask){WorkflowInstance w=get(id); synchronized(w){if(!w.tasks().containsKey(fromTask))throw new IllegalArgumentException("Unknown task: "+fromTask);w.context().requirement(newRequirement);Set<String> impacted=descendants(w,fromTask);impacted.add(fromTask);for(String x:impacted){WorkflowTask t=w.tasks().get(x);if(t!=null){t.reset();approvals.revoke(id,x);}}w.status=WorkflowStatus.PENDING;audit.record(id,fromTask,"REPLANNED","Requirement changed; reset impacted subgraph and revoked prior approvals: "+impacted);}}
 private Set<String> descendants(WorkflowInstance w,String root){Set<String> out=new LinkedHashSet<>();boolean changed;do{changed=false;for(WorkflowTask t:w.tasks().values())if(!out.contains(t.id())&&(t.dependencies().contains(root)||t.dependencies().stream().anyMatch(out::contains))){out.add(t.id());changed=true;}}while(changed);return out;}
 private boolean dependenciesComplete(WorkflowTask t,WorkflowInstance w){return t.dependencies().stream().allMatch(d->w.tasks().containsKey(d)&&w.tasks().get(d).status()==TaskStatus.COMPLETED);}
 public WorkflowInstance get(String id){WorkflowInstance w=store.get(id);if(w==null)throw new IllegalArgumentException("Unknown workflow: "+id);return w;} public List<AuditEvent> audit(String id){get(id);return audit.events(id);}
 private void validateGraph(List<WorkflowTask> tasks){Map<String,WorkflowTask> map=new HashMap<>();for(WorkflowTask t:tasks){if(map.put(t.id(),t)!=null)throw new IllegalArgumentException("Duplicate task: "+t.id());}for(WorkflowTask t:tasks)for(String d:t.dependencies())if(!map.containsKey(d))throw new IllegalArgumentException("Unknown dependency: "+d);Set<String> visiting=new HashSet<>(),visited=new HashSet<>();for(String id:map.keySet())if(cycle(id,map,visiting,visited))throw new IllegalArgumentException("Dependency graph contains a cycle");}
 private boolean cycle(String id,Map<String,WorkflowTask>m,Set<String>v,Set<String>d){if(v.contains(id))return true;if(d.contains(id))return false;v.add(id);for(String x:m.get(id).dependencies())if(cycle(x,m,v,d))return true;v.remove(id);d.add(id);return false;}
}
